/**
 * Vaerion site facts — the single measured source of truth for every page.
 *
 * LAW: every number and claim on this website comes from this file, which
 * is transcribed from measured repository surfaces:
 *   site-data/vaerion-status.json (generated by tools/status.ts, the ONE
 *   measured source written by verify.ts), spec/openapi.json,
 *   spec/errors.yaml, docs/CLI.md, docs/INSTALL.md, docs/SDK.md,
 *   packages/vaerion/coverage-baseline.json, GitHub Releases.
 * If a claim is not in this file, it must not be on the site. Limitations
 * are facts too — they carry their marker with them.
 */

export const FACTS = {
  version: "0.1.14-rc1",
  repoUrl: "https://github.com/VaerionLab/vaerion",
  releasesUrl: "https://github.com/VaerionLab/vaerion/releases",
  issuesUrl: "https://github.com/VaerionLab/vaerion/issues",
  discussionsUrl: "https://github.com/VaerionLab/vaerion/discussions",
  license: "Apache-2.0",
  author: "Auren",
  contactEmail: "auren@vaerion.dev",

  hero: "Trust infrastructure for autonomous AI systems.",
  promise:
    "Install Vaerion, connect an AI agent, run an action, and receive verifiable proof that the action followed the rules you defined — locally, deterministically, without telemetry.",

  flow: ["Identity", "Governance", "Evidence", "Verification"] as const,

  verification: {
    gates: [
      "typecheck-engine",
      "typecheck-sdk",
      "tests",
      "coverage-ratchet",
      "layerlint",
      "constitutional-check",
      "perf-budget",
      "a11y-structural",
      "repo-lint",
    ] as const,
    tests: { total: 545, suites: 43, expectations: 3932, failed: 0 },
    coverage: { lines: 86.52, branches: 90.6, modulesRatcheted: 116 },
  },

  code: {
    engineFiles: 107,
    engineLines: 22018,
    engineTestLines: 12012,
    sdkLines: 805,
    toolLines: 2886,
  },

  contracts: {
    apiPaths: 17,
    ecodes: 81,
    adrs: 21,
    specFiles: 14,
    versionSurfaces: 22,
  },

  cli: {
    bin: "vae",
    commands: [
      "init",
      "run",
      "resume",
      "explain",
      "journal",
      "doctor",
      "dev",
      "serve",
      "package",
      "provenance",
      "repo",
      "ci",
      "release",
      "tour",
      "account",
      "ai",
      "center",
    ] as const,
    shells: ["bash", "zsh", "fish", "powershell", "nushell", "xonsh"] as const,
  },

  providers: ["OpenAI", "Anthropic", "Ollama", "MockBrain (deterministic)"] as const,

  release: {
    tag: "v0.1.14-rc1",
    signing: "Ed25519 (sha256 + manifest + independent openssl verification)",
    status: "prerelease — signed, reproducible, published on GitHub Releases",
  },

  install: {
    // Honest channel map — mirrors docs/INSTALL.md (measured status column)
    channels: [
      { name: "From source", command: "git clone … && bun install --frozen-lockfile", status: "VERIFIED", available: true },
      { name: "GitHub Releases", command: "signed tarball + install.sh", status: "VERIFIED", available: true },
      { name: "npm", command: "npm install -g vaerion", status: "build verified — publish is release-train (Founder-gated)", available: false },
      { name: "PyPI", command: "pip install vaerion", status: "wheel build verified — publish is release-train (Founder-gated)", available: false },
      { name: "Homebrew / winget / dmg / rpm", command: "authored in packaging/", status: "UNVERIFIED — host-gated", available: false },
    ] as const,
  },

  sdk: {
    name: "@vaerion/sdk",
    client: "VaeClient",
    daemonClient: "VaeDaemonClient",
    entry: "new VaeDaemonClient({ base, token })",
    parity: "SDK ⇄ CLI machine parity is tested (same run ids, journal verification, receipts, redacted exports)",
  },

  daemon: {
    loopbackOnly: true,
    pairingToken: true,
    transport: "HTTP + SSE on 127.0.0.1 — refuses any non-loopback bind",
  },

  milestones: [
    "MS-0 Skeleton and Law-in-Repo",
    "MS-1 Runtime Spine",
    "MS-2 Permission Broker",
    "MS-3 Model Gateway",
    "MS-4 Intelligence + Agents",
    "MS-5 Surfaces",
    "MS-6 Packaging + Hardening",
  ] as const,

  notYet: [
    "No cloud service — the engine is local; cloud seams are reserved (ADR-0017), not sold.",
    "No telemetry, no analytics, no undeclared network — enforced mechanically on every build.",
    "npm / PyPI publish is Founder-gated (release train); until then install from source or signed release tarballs.",
    "vaerion.dev installer URL goes live with the release train; install from Releases today.",
    "Single-binary installers (brew/winget/dmg/rpm) are authored but host-gated UNVERIFIED.",
  ] as const,

  // The hero terminal — a faithful distillation of docs/QUICKSTART.md §2–4
  // (real commands; output shape measured from the quickstart narrative).
  heroTerminal: [
    { kind: "cmd" as const, text: "vae init --template demo" },
    { kind: "out" as const, text: "workspace ready · vaerion.yaml + .vaerion/" },
    { kind: "cmd" as const, text: 'vae run demo --sources ./sources --query "determinism"' },
    { kind: "out" as const, text: "indexed sources · broker-gated pipeline · journaled" },
    { kind: "gold" as const, text: "run_01J9…  receipt folded  ✔ closed" },
    { kind: "cmd" as const, text: "vae journal verify run_01J9…" },
    { kind: "ok" as const, text: "ok: true  chain: intact  events: 42  blake3 ✓" },
    { kind: "cmd" as const, text: "vae package build" },
    { kind: "out" as const, text: "vaerion-demo.vxn  →  byte-identical rebuild ✓" },
    { kind: "cmd" as const, text: "vae package verify .vaerion/package/vaerion-demo.vxn" },
    { kind: "ok" as const, text: "digests recomputed · pins compared · pure check ✓" },
  ],
} as const;
