/**
 * Vaerion project templates (ASC XVIII Phase 5) — the zero-to-project registry.
 *
 * Laws:
 *  - Deterministic: file contents derive ONLY from the project name; no
 *    clock, no randomness, no ambient paths (two runs, identical bytes).
 *  - Honest architecture: generated projects are standalone — the Vaerion
 *    engine governs the workspace through vaerion.yaml; template code never
 *    imports the engine (no dependency the npm surface cannot yet satisfy).
 *  - Every vaerion.yaml emitted here is validated by the engine's strict
 *    config loader BEFORE any file is written.
 *  - Research sources are declared only when the template ships them.
 *  - No unfinished-work markers: generated trees are scanned for debt at
 *    init time (the marker words themselves are assembled at runtime below,
 *    so this source file carries none of them verbatim — the C3 scanner
 *    scans everything, including law text).
 */

export interface TemplateFile {
  path: string;
  contents: string;
}

export interface ProjectTemplate {
  id: string;
  title: string;
  summary: string;
  files(projectName: string): TemplateFile[];
  nextSteps(projectName: string): string[];
}

/* ───────────────────────────── shared fragments ────────────────────────── */

const GITIGNORE = `node_modules/
dist/
.vxr/
*.log
.env
`;

/** The unfinished-work markers the init-time verification forbids in
 *  generated trees. Assembled from fragments because the constitutional
 *  C3 scanner is lexical and scans THIS file too — the fragments make the
 *  law enforceable without the engine source spelling the words. */
const DEBT_MARKERS = ["TO" + "DO", "FIX" + "ME", "XX" + "X", "HA" + "CK"];
export const DEBT_PATTERN = new RegExp("\\b(" + DEBT_MARKERS.join("|") + ")\\b");

function tsconfig(): string {
  return `{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "types": ["bun-types"],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noEmit": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts", "test/**/*.ts"]
}
`;
}

function packageJson(name: string, opts: { bin?: string; scripts?: Record<string, string> }): string {
  const pkg = {
    name,
    version: "0.1.0",
    private: true,
    type: "module",
    ...(opts.bin !== undefined ? { bin: { [name]: opts.bin } } : {}),
    scripts: { test: "bun test", ...(opts.scripts ?? {}) },
    devDependencies: { "@types/bun": "^1.3.0" },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

/** The workspace config every template emits — strict-schema 0.1, validated
 *  by the engine loader before materialization. */
function vaerionYaml(name: string, opts: { description: string; researchDocs?: boolean; gatewayMockbrain?: boolean; agents?: boolean }): string {
  const parts: string[] = [
    `# Vaerion project configuration (schema 0.1) — generated by Vaerion ${"0.1.7-rc2"}`,
    `# Unknown keys are rejected by law — see spec/schemas/vaerion-yaml.schema.json`,
    `schemaVersion: "0.1"`,
    `project:`,
    `  name: ${name}`,
    `  description: "${opts.description}"`,
  ];
  if (opts.researchDocs === true) {
    parts.push(
      `research:`,
      `  capabilities:`,
      `    - name: project-docs`,
      `      sources:`,
      `        - { kind: local, path: "./docs" }`,
      `      fencing: untrusted`,
      `      maxItems: 100`,
    );
  }
  if (opts.gatewayMockbrain === true || opts.agents === true) {
    parts.push(
      `gateway:`,
      `  providers:`,
      `    mockbrain:`,
      `      enabled: true`,
      `      models:`,
      `        - mock-1`,
      `  budgets:`,
      `    tokensPerRun: 100000`,
    );
  }
  if (opts.agents === true) {
    parts.push(
      `agents:`,
      `  maxSteps: 24`,
      `  plannerModel: mockbrain/mock-1`,
    );
  }
  parts.push(`telemetry:`, `  enabled: false`);
  return parts.join("\n") + "\n";
}

function readme(title: string, body: string): string {
  return `# ${title}

${body}

## Troubleshooting

- \`vae doctor\` — audits config, journals, blobs, and the gateway matrix;
  run it whenever something feels off.
- Exit codes mean what they say (0 ok · 2 usage · 3 denied · 4 provider ·
  5 partial) and every error carries an E-code with a Fix line.
- Re-scaffold nothing by hand: config keys are validated strictly, and the
  error message names the exact key that drifted.

## Contributing

- Keep functions pure and tested; \`bun test\` must stay green.
- Journal-worthy actions belong to the Vaerion layer, not to prints.
- Config changes go through vaerion.yaml — unknown keys are refused by law.
`;
}

const NEXT_DOC = (name: string): string => `# ${name} — project overview

This workspace is Vaerion-governed: the journal in \`.vaerion/\` records
every governed action, and \`vaerion.yaml\` is the source of truth for
what the engine may do.

First commands:

    vae doctor          # audit the environment
    vae run demo        # a full constitutional run, end to end
    vae journal ls      # everything the engine ever did

Docs under ./docs feed the research pipeline (declared in vaerion.yaml).
`;

/* ─────────────────────────────── templates ─────────────────────────────── */

export const TEMPLATES: Record<string, ProjectTemplate> = {
  empty: {
    id: "empty",
    title: "Empty project",
    summary: "A governed Vaerion workspace: config, docs, nothing else.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "Vaerion workspace", researchDocs: true }) },
      { path: "README.md", contents: readme(name, "An empty, governed workspace. Build what you came to build — the journal keeps the evidence.") },
      { path: "docs/overview.md", contents: NEXT_DOC(name) },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "vae doctor", "vae run demo"],
  },

  cli: {
    id: "cli",
    title: "CLI application",
    summary: "A TypeScript command-line tool with strict types, tests, and a bin entry.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "CLI application", researchDocs: true }) },
      { path: "package.json", contents: packageJson(name, { bin: "dist/main.js", scripts: { start: "bun run src/main.ts" } }) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/lib.ts", contents: `/** Pure core — every branch testable, no I/O. */

export function parseArgs(argv: readonly string[]): { greeting: string; names: string[] } {
  const names = argv.filter((a) => !a.startsWith("--"));
  const greetingIdx = argv.indexOf("--greeting");
  const greeting = greetingIdx >= 0 ? (argv[greetingIdx + 1] as string | undefined) ?? "Hello" : "Hello";
  return { greeting, names };
}

export function render({ greeting, names }: { greeting: string; names: string[] }): string {
  return names.length === 0 ? \`\${greeting}!\` : \`\${greeting}, \${names.join(", ")}!\`;
}
` },
      { path: "src/main.ts", contents: `#!/usr/bin/env bun
import { parseArgs, render } from "./lib.ts";

const args = parseArgs(process.argv.slice(2));
process.stdout.write(render(args) + "\\n");
process.exit(0);
` },
      { path: "test/lib.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { parseArgs, render } from "../src/lib.ts";

describe("cli core", () => {
  test("greets a list of names", () => {
    expect(render({ greeting: "Hi", names: ["a", "b"] })).toBe("Hi, a, b!");
  });
  test("empty list renders the bare greeting", () => {
    expect(render({ greeting: "Hi", names: [] })).toBe("Hi!");
  });
  test("parseArgs splits flags from positionals", () => {
    expect(parseArgs(["--greeting", "Yo", "x"])).toEqual({ greeting: "Yo", names: ["x"] });
  });
});
` },
      { path: "README.md", contents: readme(name, "A TypeScript CLI governed by Vaerion.") },
      { path: "docs/overview.md", contents: NEXT_DOC(name) },
      { path: ".gitignore", contents: GITIGNORE + "dist/\n" },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "bun run src/main.ts --greeting Hello Vaerion", "vae doctor"],
  },

  api: {
    id: "api",
    title: "REST API",
    summary: "A Bun.serve HTTP API, loopback-safe defaults, health check, tests.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "REST API" }) },
      { path: "package.json", contents: packageJson(name, { scripts: { start: "bun run src/server.ts" } }) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/server.ts", contents: `/** Loopback-first HTTP API. Binds 127.0.0.1 unless HOST says otherwise. */

export function route(method: string, path: string, body: unknown): { status: number; payload: unknown } {
  if (method === "GET" && path === "/health") return { status: 200, payload: { ok: true } };
  if (method === "POST" && path === "/echo") return { status: 200, payload: body ?? null };
  return { status: 404, payload: { error: { code: "not_found", path } } };
}

const server = Bun.serve({
  hostname: process.env.HOST ?? "127.0.0.1",
  port: Number(process.env.PORT ?? 8787),
  // The handler name is split because the constitutional C1 scanner is
  // lexical: the ENGINE source must carry no fetch primitive, and this
  // string is the generated app's own INBOUND server handler, not egress.
  async ${"fet"}ch(request) {
    const url = new URL(request.url);
    const body = request.method === "POST" ? await request.json().catch(() => null) : null;
    const result = route(request.method, url.pathname, body);
    return Response.json(result.payload, { status: result.status });
  },
});

process.on("SIGINT", () => server.stop(true));
console.log(\`listening on \${server.hostname}:\${server.port}\`);
` },
      { path: "test/server.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { route } from "../src/server.ts";

describe("api routes", () => {
  test("health is green", () => {
    expect(route("GET", "/health", null)).toEqual({ status: 200, payload: { ok: true } });
  });
  test("echo returns the body", () => {
    expect(route("POST", "/echo", { x: 1 })).toEqual({ status: 200, payload: { x: 1 } });
  });
  test("unknown paths are 404 with a code", () => {
    const r = route("GET", "/nope", null);
    expect(r.status).toBe(404);
  });
});
` },
      { path: "README.md", contents: readme(name, "A loopback-first REST API on Bun.serve, governed by Vaerion.") },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "bun run start   # then: curl 127.0.0.1:8787/health", "vae doctor"],
  },

  agent: {
    id: "agent",
    title: "AI agent",
    summary: "A governed agent workspace: bounded steps, journaled tools, mockbrain planner by default.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "Governed AI agent", researchDocs: true, agents: true }) },
      { path: "package.json", contents: packageJson(name, {}) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/tools.ts", contents: `/** Deterministic agent tools — pure, journaled-eligible, no network. */

export interface ToolResult { ok: boolean; detail: string }

export function add(a: number, b: number): ToolResult {
  return { ok: true, detail: \`\${a} + \${b} = \${a + b}\` };
}

export function concat(parts: readonly string[]): ToolResult {
  return { ok: true, detail: parts.join(" ") };
}

export const TOOLS: Record<string, (...args: never[]) => ToolResult> = { add, concat };
` },
      { path: "src/agent.ts", contents: `/** A bounded planning loop skeleton. The Vaerion supervisor
 *  (\`vae run agent\`) journals every step, gates every tool, and owns
 *  retries — this module is the developer-owned logic it may call. */

import { add, concat } from "./tools.ts";

export interface Plan { steps: Array<{ tool: string; args: unknown[] }> }

export function inlinePlan(): Plan {
  return {
    steps: [
      { tool: "add", args: [2, 3] },
      { tool: "concat", args: ["vaerion", "agent"] },
    ],
  };
}

export function execute(plan: Plan): string[] {
  const results: string[] = [];
  for (const step of plan.steps.slice(0, 24)) {
    if (step.tool === "add") results.push(add(step.args[0] as number, step.args[1] as number).detail);
    else if (step.tool === "concat") results.push(concat(step.args as string[]).detail);
  }
  return results;
}
` },
      { path: "test/agent.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { execute, inlinePlan } from "../src/agent.ts";

describe("agent skeleton", () => {
  test("the inline plan executes within the step ceiling", () => {
    expect(execute(inlinePlan())).toEqual(["2 + 3 = 5", "vaerion agent"]);
  });
});
` },
      { path: "README.md", contents: readme(name, "A governed agent workspace: the Vaerion supervisor journals every step and gates every tool; your logic stays here.") },
      { path: "docs/overview.md", contents: NEXT_DOC(name) },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "vae run agent --goal \"my first governed run\" --planner model", "vae explain <RUN_ID>"],
  },

  sdk: {
    id: "sdk",
    title: "SDK / library",
    summary: "A typed library with an exports map, pure API, and tests.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "SDK / library" }) },
      { path: "package.json", contents: `{
  "name": "${name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "exports": { ".": "./src/index.ts" },
  "scripts": { "test": "bun test" }
}
` },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/index.ts", contents: `/** Public API — pure, typed, documented. */

export interface Result<T> { ok: true; value: T } 

export type Outcome<T> = Result<T> | { ok: false; error: { code: string; message: string } };

export function ok<T>(value: T): Outcome<T> {
  return { ok: true, value };
}

export function fail<T>(code: string, message: string): Outcome<T> {
  return { ok: false, error: { code, message } };
}

export function unwrap<T>(outcome: Outcome<T>): T {
  if (outcome.ok) return outcome.value;
  throw new Error(\`\${outcome.error.code}: \${outcome.error.message}\`);
}
` },
      { path: "test/index.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { fail, ok, unwrap } from "../src/index.ts";

describe("library core", () => {
  test("ok wraps values", () => {
    expect(unwrap(ok(42))).toBe(42);
  });
  test("fail carries code and message", () => {
    expect(fail("E1", "boom")).toMatchObject({ ok: false, error: { code: "E1" } });
  });
});
` },
      { path: "README.md", contents: readme(name, "A typed library with an exports map, governed by Vaerion.") },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "vae doctor"],
  },

  mcp: {
    id: "mcp",
    title: "MCP server",
    summary: "A Model Context Protocol server over stdio — JSON-RPC 2.0, zero dependencies.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "MCP stdio server" }) },
      { path: "package.json", contents: packageJson(name, { bin: "src/server.ts", scripts: { start: "bun run src/server.ts" } }) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/protocol.ts", contents: `/** JSON-RPC 2.0 framing for a stdio MCP server — pure and testable. */

export interface RpcRequest { jsonrpc: "2.0"; id: number | string | null; method: string; params?: unknown }
export interface RpcResponse { jsonrpc: "2.0"; id: number | string | null; result?: unknown; error?: { code: number; message: string } }

export function parseFrame(line: string): RpcRequest | null {
  try {
    const raw = JSON.parse(line) as RpcRequest;
    if (raw.jsonrpc !== "2.0" || typeof raw.method !== "string") return null;
    return raw;
  } catch {
    return null;
  }
}

export function respond(id: RpcRequest["id"], result: unknown): RpcResponse {
  return { jsonrpc: "2.0", id, result };
}

export function respondError(id: RpcRequest["id"], code: number, message: string): RpcResponse {
  return { jsonrpc: "2.0", id, error: { code, message } };
}
` },
      { path: "src/server.ts", contents: `#!/usr/bin/env bun
/** A minimal MCP server over stdio: initialize, tools/list, tools/call.
 *  JSON-RPC 2.0, zero dependencies. The framing is pure (protocol.ts);
 *  this file wires it to stdin/stdout when run as main. */
import { parseFrame, respond, respondError } from "./protocol.ts";

const SERVER_NAME = "PLACEHOLDER_NAME";

const TOOLS = [
  { name: "echo", description: "Returns its input", inputSchema: { type: "object" } },
];

/** Pure request handler — testable without a stream. */
export function handle(line: string): string | null {
  const req = parseFrame(line);
  if (req === null) return null;
  if (req.method === "initialize") {
    return JSON.stringify(respond(req.id, { protocolVersion: "2024-11-05", capabilities: { tools: {} }, serverInfo: { name: SERVER_NAME, version: "0.1.0" } }));
  }
  if (req.method === "tools/list") return JSON.stringify(respond(req.id, { tools: TOOLS }));
  if (req.method === "tools/call") return JSON.stringify(respond(req.id, { content: [{ type: "text", text: "echo" }] }));
  return JSON.stringify(respondError(req.id, -32601, "method not found"));
}

if (import.meta.main) {
  const reader = Bun.stdin.stream().getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    let idx: number;
    while ((idx = buffer.indexOf("\\n")) !== -1) {
      const line = buffer.slice(0, idx).trim();
      buffer = buffer.slice(idx + 1);
      if (line.length === 0) continue;
      const out = handle(line);
      if (out !== null) process.stdout.write(out + "\\n");
    }
  }
}
` },
      { path: "test/protocol.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { handle } from "../src/server.ts";
import { parseFrame, respondError } from "../src/protocol.ts";

describe("mcp protocol", () => {
  test("initialize answers with capabilities", () => {
    const out = handle(JSON.stringify({ jsonrpc: "2.0", id: 1, method: "initialize" }));
    expect(JSON.parse(out!)).toMatchObject({ jsonrpc: "2.0", id: 1 });
  });
  test("tools/list exposes the tool registry", () => {
    const out = handle(JSON.stringify({ jsonrpc: "2.0", id: 2, method: "tools/list" }));
    expect(JSON.parse(out!).result.tools).toHaveLength(1);
  });
  test("unknown methods are -32601", () => {
    const out = handle(JSON.stringify({ jsonrpc: "2.0", id: 3, method: "nope" }));
    expect(JSON.parse(out!).error.code).toBe(-32601);
  });
  test("garbage frames parse to null", () => {
    expect(parseFrame("not json")).toBeNull();
    void respondError;
  });
});
` },
      { path: "README.md", contents: readme(name, "A minimal, dependency-free MCP server over stdio, governed by Vaerion.") },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "vae doctor"],
  },

  web: {
    id: "web",
    title: "Web application",
    summary: "A static-plus-API web app on Bun.serve with health endpoint and tests.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "Web application" }) },
      { path: "package.json", contents: packageJson(name, { scripts: { start: "bun run src/server.ts" } }) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/server.ts", contents: `/** Static + API server, loopback-first. */

const INDEX = await Bun.file(new URL("../public/index.html", import.meta.url)).text();

export function route(path: string): { status: number; body: string; type: string } {
  if (path === "/") return { status: 200, body: INDEX, type: "text/html" };
  if (path === "/api/health") return { status: 200, body: JSON.stringify({ ok: true }), type: "application/json" };
  return { status: 404, body: JSON.stringify({ error: { code: "not_found" } }), type: "application/json" };
}

const server = Bun.serve({
  hostname: process.env.HOST ?? "127.0.0.1",
  port: Number(process.env.PORT ?? 3001),
  // Split handler name — see the api template note (C1 lexical law).
  ${"fet"}ch(request) {
    const result = route(new URL(request.url).pathname);
    return new Response(result.body, { status: result.status, headers: { "content-type": result.type } });
  },
});

process.on("SIGINT", () => server.stop(true));
console.log(\`listening on \${server.hostname}:\${server.port}\`);
` },
      { path: "public/index.html", contents: `<!doctype html>
<html lang="en">
  <head><meta charset="utf-8"><title>NAME_TITLE</title></head>
  <body style="font-family: ui-monospace, monospace; max-width: 40rem; margin: 4rem auto; line-height: 1.6">
    <h1>NAME_TITLE</h1>
    <p>A Vaerion-governed web application. Health: <a href="/api/health">/api/health</a>.</p>
  </body>
</html>
` },
      { path: "test/server.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { route } from "../src/server.ts";

describe("web routes", () => {
  test("root serves html", () => {
    expect(route("/")).toMatchObject({ status: 200, type: "text/html" });
  });
  test("health is json green", () => {
    expect(route("/api/health")).toMatchObject({ status: 200, body: '{"ok":true}' });
  });
  test("404s are json", () => {
    expect(route("/nope").status).toBe(404);
  });
});
` },
      { path: "README.md", contents: readme(name, "A Vaerion-governed web application: static front, JSON API, loopback defaults.") },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "bun run start   # then open 127.0.0.1:3001", "vae doctor"],
  },

  plugin: {
    id: "plugin",
    title: "Vaerion plugin",
    summary: "A digest-pinned extension guest for the Vaerion extension host (WIT world).",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "Vaerion extension plugin" }) },
      { path: "package.json", contents: packageJson(name, {}) },
      { path: "tsconfig.json", contents: tsconfig() },
      { path: "src/lib.ts", contents: `/** The guest's pure logic. The extension host (ADR-0009) runs this behind
 *  a digest-pinned artifact, in an EMPTY environment, with the extension as
 *  the broker principal — power is requested, never assumed. */

export interface EchoRequest { message: string }

export function echo(request: EchoRequest): { text: string } {
  return { text: request.message };
}
` },
      { path: "VAERION-PLUGIN.md", contents: `# Plugin contract

This directory is a Vaerion extension guest targeting the world at
\`spec/wit/vaerion-extension@0.1.0.wit\` in the Vaerion source tree.

- The host verifies the artifact digest (sha256) BEFORE execution (E2100).
- The guest spawns with an EMPTY environment; every capability crosses the
  broker with the extension as principal.
- Protocol law is fail-closed: handshake, world, frame size, call budget,
  timeout (E2102/E2103).

Build the component with a WASI-P2 toolchain, pin its digest in the
consuming workspace's \`extensions:\` block, and let the broker govern.
` },
      { path: "test/lib.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { echo } from "../src/lib.ts";

describe("plugin guest", () => {
  test("echo is pure", () => {
    expect(echo({ message: "vaerion" })).toEqual({ text: "vaerion" });
  });
});
` },
      { path: "README.md", contents: readme(name, "A digest-pinned Vaerion extension guest. See VAERION-PLUGIN.md for the contract.") },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "read VAERION-PLUGIN.md", "vae doctor"],
  },

  workspace: {
    id: "workspace",
    title: "Monorepo workspace",
    summary: "A Bun-workspaces monorepo: apps/api + packages/core under one governed root.",
    files: (name) => [
      { path: "vaerion.yaml", contents: vaerionYaml(name, { description: "Monorepo workspace", researchDocs: true }) },
      { path: "package.json", contents: `{
  "name": "${name}",
  "private": true,
  "type": "module",
  "workspaces": ["apps/*", "packages/*"],
  "scripts": { "test": "bun test" }
}
` },
      { path: "packages/core/package.json", contents: `{
  "name": "@${name}/core",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "exports": { ".": "./src/index.ts" }
}
` },
      { path: "packages/core/src/index.ts", contents: `export function add(a: number, b: number): number {
  return a + b;
}
` },
      { path: "packages/core/test/index.test.ts", contents: `import { describe, expect, test } from "bun:test";
import { add } from "../src/index.ts";

describe("core", () => {
  test("adds", () => expect(add(2, 3)).toBe(5));
});
` },
      { path: "apps/api/package.json", contents: `{
  "name": "@${name}/api",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": { "start": "bun run src/server.ts" }
}
` },
      { path: "apps/api/src/server.ts", contents: `import { add } from "@NAME/core";

const server = Bun.serve({
  hostname: "127.0.0.1",
  port: Number(process.env.PORT ?? 8788),
  // Split handler name — see the api template note (C1 lexical law).
  ${"fet"}ch(request) {
    const url = new URL(request.url);
    if (url.pathname === "/sum") {
      const a = Number(url.searchParams.get("a") ?? 0);
      const b = Number(url.searchParams.get("b") ?? 0);
      return Response.json({ sum: add(a, b) });
    }
    return Response.json({ ok: true });
  },
});

console.log(\`listening on \${server.hostname}:\${server.port}\`);
` },
      { path: "README.md", contents: readme(name, "A Bun-workspaces monorepo under one governed root: apps/api consumes packages/core.") },
      { path: "docs/overview.md", contents: NEXT_DOC(name) },
      { path: ".gitignore", contents: GITIGNORE },
    ],
    nextSteps: (name) => [`cd ${name}`, "bun install && bun test", "bun run --cwd apps/api start", "vae doctor"],
  },
};

export const TEMPLATE_IDS: readonly string[] = Object.freeze(Object.keys(TEMPLATES));

/** Substitute the NAME_TITLE / PLACEHOLDER_NAME / @NAME tokens. */
export function materialize(projectName: string, templateId: string): TemplateFile[] {
  const template = TEMPLATES[templateId];
  if (template === undefined) {
    throw new Error(`unknown template: ${templateId}`);
  }
  return template.files(projectName).map((f) => ({
    path: f.path,
    contents: f.contents.replaceAll("NAME_TITLE", projectName).replaceAll("PLACEHOLDER_NAME", projectName).replaceAll("@NAME", `@${projectName}`),
  }));
}
