"use client";

import { ShieldCheck, GitBranch, FileCode2, ListChecks, Scale, FlaskConical, ArrowRight, Gauge, History, Wallet, Terminal, PackageCheck, BookOpen } from "lucide-react";
import { PageHero, Section, Panel, Pill, Honesty } from "../primitives";
import { cn } from "@/lib/utils";

/* ════════════════════════════════════════════════════════════════════════
 * Engine status — the measured dashboard, preserved from the original
 * private face and re-skinned into the public site. Data is loaded
 * server-side by src/app/page.tsx from site-data/vaerion-status.json
 * (generated by tools/status.ts — the ONE measured source) and passed in.
 * Every claim on this page is measured; nothing here is narrated.
 * ════════════════════════════════════════════════════════════════════════ */

export interface Status {
  generatedAt: string;
  engineVersion: string;
  substrate: string;
  verification: { ok: boolean; generatedAt: string | null; gates: Array<{ gate: string; ok: boolean; durationMs: number }> };
  tests: { suites: number; assertedExpectations: number; totalTests: number };
  code: { engine: { files: number; lines: number }; engineTests: { files: number; lines: number }; sdk: { files: number; lines: number }; tools: { files: number; lines: number } };
  contracts: { specFiles: string[]; adrCount: number };
  milestones: Array<{ id: string; name: string; status: string; progress: number; evidence: string }>;
  overallProgress: number;
  phaseLedger?: Array<{ id: string; phase: string; status: string; evidence: string }>;
  release?: { measured: boolean; ready?: boolean; verdict?: string; passed?: number; total?: number; blockers: string[]; note?: string };
  commandCenter?: {
    workspace: { root: string; runs: number };
    operations: { runs: Array<{ run_id: string; records: number; events: number; verified: boolean; receipt: boolean }>; journals_verified: boolean; receipts: number; metering: { invocations: number; failed: number; inputTokens: number; outputTokens: number; totalMicroUsd: number }; blob_refs: { checked: number; failed: number } };
    integrity: { audit_ledger: { ok: boolean; entries: number; detail: string }; refusal_log: { ok: boolean; entries: number; detail: string } };
    read_only: string;
  };
  risks: string[];
  nextWork: string[];
}

function StatRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="flex items-center gap-3 text-sm">
      <span className="text-mutedfg">{icon}</span>
      <span className="w-28 shrink-0 text-mutedfg">{label}</span>
      <span className="font-medium text-body">{value}</span>
    </div>
  );
}

function Progress({ value, tone = "trust", label }: { value: number; tone?: "trust" | "warn"; label: string }) {
  return (
    <div
      className="h-1.5 w-full overflow-hidden rounded-full bg-surface-2"
      role="progressbar"
      aria-label={label}
      aria-valuenow={value}
      aria-valuemin={0}
      aria-valuemax={100}
    >
      <div className={cn("h-full rounded-full", tone === "trust" ? "bg-trust" : "bg-warnx")} style={{ width: `${value}%` }} />
    </div>
  );
}

export default function StatusPage({ status }: { status: Status | null }) {
  return (
    <>
      <PageHero
        eyebrow="Engine status · measured"
        title="The engine, measured — not narrated."
        lead="Every claim below is read from site-data/vaerion-status.json, generated by tools/status.ts and fed by the verification gates. If a measurement is missing, the page says so."
      >
        <div className="flex flex-wrap items-center gap-2">
          <Pill tone={status?.verification.ok ? "trust" : "fail"}>
            <ShieldCheck className="h-3 w-3" aria-hidden />
            {status?.verification.ok ? "ALL VERIFICATION GATES GREEN" : "verification pending"}
          </Pill>
          {status ? <Pill tone="gold">engine {status.engineVersion}</Pill> : null}
          <Honesty tone="info">read-only</Honesty>
        </div>
      </PageHero>

      <Section tight label="Install" title="Install — the measured paths, honestly labeled.">
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <Panel className="p-6">
            <p className="flex items-center gap-2 text-sm font-semibold text-body">
              <Terminal className="h-4 w-4 text-gold" aria-hidden /> Install from source — the measured path
            </p>
            <p className="mt-2 text-sm text-mutedfg">
              The path the Empty Machine Test executed end-to-end on a fresh $HOME: install, verify, init, first run, upgrade, clean removal.
            </p>
            <pre className="vx-scroll mt-4 overflow-x-auto rounded-xl border border-edge bg-[#0B0D10] p-3 font-mono text-xs leading-relaxed text-[#D7DAE0]" aria-label="Install commands">
              {"git clone https://github.com/VaerionLab/vaerion.git\ncd vaerion && ./packaging/install.sh\nvae doctor && vae init"}
            </pre>
            <p className="mt-3 text-xs text-mutedfg">
              Needs the Bun runtime (1.2+). The installer teaches every step, persists PATH on a fresh home, and <code className="font-mono">--uninstall</code> removes everything it created.
            </p>
            <div className="mt-3 flex flex-wrap gap-2">
              <Pill tone="trust">measured on Linux</Pill>
              <Pill>offline-capable at the release tag</Pill>
            </div>
          </Panel>
          <Panel className="p-6">
            <p className="flex items-center gap-2 text-sm font-semibold text-body">
              <PackageCheck className="h-4 w-4 text-gold" aria-hidden /> Package channels — authored, honestly labeled
            </p>
            <p className="mt-2 text-sm text-mutedfg">
              Every manifest exists and is version-locked to the engine register. Registry publication and host-platform verification are
              Founder/external gates — never claimed here.
            </p>
            <div className="mt-4 flex flex-wrap gap-2">
              {[
                ["npm tarball", "consumer install measured", true],
                ["Python wheel", "offline pip measured", true],
                ["Homebrew", "UNVERIFIED — host", false],
                ["winget", "UNVERIFIED — host", false],
                ["deb / rpm", "UNVERIFIED — host", false],
                ["AppImage", "UNVERIFIED — host", false],
                ["DMG / PKG", "UNVERIFIED — host", false],
              ].map(([name, label, ok]) => (
                <Pill key={name as string} tone={ok ? "trust" : "warn"}>
                  {name} · {label}
                </Pill>
              ))}
            </div>
            <p className="mt-3 text-xs text-mutedfg">
              Release artifacts verify in under a minute without this repository: <code className="font-mono">sha256sum --check SHA256SUMS</code>, then the
              Ed25519 check taught in the shipped VERIFY.md (key ships beside the artifacts).
            </p>
          </Panel>
        </div>
      </Section>

      <Section tight label="Roadmap" title="Roadmap progress">
        <div className="mb-3 flex items-baseline justify-between">
          <span className="text-sm text-mutedfg">MS-0 → GA</span>
          {status ? <span className="text-sm text-mutedfg">{status.overallProgress}%</span> : null}
        </div>
        <Progress value={status?.overallProgress ?? 0} label="Overall roadmap progress" />
        {status ? (
          <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {status.milestones.map((m) => (
              <Panel key={m.id} className="p-4">
                <div className="flex items-center justify-between gap-2">
                  <p className="text-sm font-semibold text-body">
                    {m.id} · {m.name}
                  </p>
                  <span className="font-mono text-xs text-mutedfg">{m.progress}%</span>
                </div>
                <p className="mb-2 mt-1 text-xs text-mutedfg">{m.status === "complete" ? "complete" : m.status === "in_progress" ? "in progress" : "pending"}</p>
                <Progress value={m.progress} label={`${m.id} ${m.name} progress`} />
                <p className="mt-2 line-clamp-4 text-xs leading-relaxed text-mutedfg">{m.evidence}</p>
              </Panel>
            ))}
          </div>
        ) : null}
      </Section>

      <Section tight label="Verification" title="Verification gates & built inventory">
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <Panel className="p-6">
            <p className="flex items-center gap-2 text-sm font-semibold text-body">
              <ListChecks className="h-4 w-4 text-gold" aria-hidden /> Verification gates
            </p>
            <p className="mt-1 text-xs text-mutedfg">
              {status?.verification.generatedAt ? `run ${new Date(status.verification.generatedAt).toISOString().slice(0, 16).replace("T", " ")} UTC` : "awaiting first run"}
            </p>
            <div className="mt-4 space-y-2">
              {(status?.verification.gates ?? []).map((g) => (
                <div key={g.gate} className="flex items-center justify-between text-sm">
                  <span className="font-mono text-xs sm:text-sm">{g.gate}</span>
                  <span className="flex items-center gap-2">
                    <span className="text-xs text-mutedfg">{g.durationMs}ms</span>
                    {g.ok ? <Pill tone="trust">GREEN</Pill> : <Pill tone="fail">RED</Pill>}
                  </span>
                </div>
              ))}
              {!status ? <p className="text-sm text-mutedfg">status data unavailable</p> : null}
            </div>
          </Panel>
          <Panel className="p-6">
            <p className="flex items-center gap-2 text-sm font-semibold text-body">
              <FlaskConical className="h-4 w-4 text-gold" aria-hidden /> Built &amp; tested inventory
            </p>
            <p className="mt-1 text-xs text-mutedfg">measured, not narrated</p>
            <div className="mt-4 space-y-2.5">
              {status ? (
                <>
                  <StatRow icon={<FileCode2 className="h-4 w-4" aria-hidden />} label="engine source" value={`${status.code.engine.files} files · ${status.code.engine.lines.toLocaleString()} lines`} />
                  <StatRow icon={<FlaskConical className="h-4 w-4" aria-hidden />} label="tests" value={`${status.tests.totalTests} tests · ${status.tests.assertedExpectations} expectations · ${status.tests.suites} suites`} />
                  <StatRow icon={<Scale className="h-4 w-4" aria-hidden />} label="contracts" value={`${status.contracts.specFiles.length} spec files · ${status.contracts.adrCount} ADRs`} />
                  <StatRow icon={<GitBranch className="h-4 w-4" aria-hidden />} label="tooling + sdk" value={`${status.code.tools.files} tool files · ${status.code.sdk.files} sdk files`} />
                </>
              ) : (
                <p className="text-sm text-mutedfg">status data unavailable</p>
              )}
            </div>
          </Panel>
        </div>
      </Section>

      {status?.commandCenter ? (
        <Section tight label="Command center" title="Command center">
          <p className="-mt-6 mb-6 text-xs text-mutedfg">one measured core — `vae center` · tools/status.ts (D-S)</p>
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
            <Panel className="p-6">
              <p className="flex items-center gap-2 text-sm font-semibold text-body">
                <Gauge className="h-4 w-4 text-gold" aria-hidden /> Release readiness
              </p>
              <p className="mt-1 text-xs text-mutedfg">fail-closed · measured, never estimated</p>
              <div className="mt-4 space-y-2 text-sm">
                {status.release?.measured ? (
                  <>
                    <div className="flex items-center justify-between">
                      <span className="font-semibold text-body">{status.release.verdict}</span>
                      <Pill tone={status.release.ready ? "trust" : "warn"}>
                        {status.release.passed}/{status.release.total} checks
                      </Pill>
                    </div>
                    <ul className="list-inside list-disc space-y-1 text-xs text-mutedfg">
                      {status.release.blockers.slice(0, 4).map((b, i) => (
                        <li key={i}>{b}</li>
                      ))}
                      {status.release.blockers.length === 0 && <li>no blockers measured</li>}
                    </ul>
                  </>
                ) : (
                  <p className="text-xs text-mutedfg">{status.release?.note ?? "not measured"}</p>
                )}
              </div>
            </Panel>
            <Panel className="p-6">
              <p className="flex items-center gap-2 text-sm font-semibold text-body">
                <Wallet className="h-4 w-4 text-gold" aria-hidden /> Demo workspace cockpit
              </p>
              <p className="mt-1 text-xs text-mutedfg">examples/vaerion-demo · the same fold `vae center` renders</p>
              <div className="mt-4 space-y-2.5">
                <StatRow icon={<History className="h-4 w-4" aria-hidden />} label="runs" value={`${status.commandCenter.workspace.runs} journaled · ${status.commandCenter.operations.receipts} receipted`} />
                <StatRow icon={<FlaskConical className="h-4 w-4" aria-hidden />} label="journals" value={status.commandCenter.operations.journals_verified ? "all chains verified" : "VERIFICATION FAILURE"} />
                <StatRow icon={<Wallet className="h-4 w-4" aria-hidden />} label="metering" value={`${status.commandCenter.operations.metering.invocations} invocations · ${status.commandCenter.operations.metering.inputTokens}in/${status.commandCenter.operations.metering.outputTokens}out tokens`} />
                <StatRow icon={<ShieldCheck className="h-4 w-4" aria-hidden />} label="integrity" value={`audit ${status.commandCenter.integrity.audit_ledger.ok ? "intact" : "BROKEN"} (${status.commandCenter.integrity.audit_ledger.entries}) · refusals ${status.commandCenter.integrity.refusal_log.ok ? "intact" : "BROKEN"} (${status.commandCenter.integrity.refusal_log.entries})`} />
              </div>
            </Panel>
            <Panel className="p-6">
              <p className="flex items-center gap-2 text-sm font-semibold text-body">
                <History className="h-4 w-4 text-gold" aria-hidden /> Phase program (D-T)
              </p>
              <p className="mt-1 text-xs text-mutedfg">reconciled at every phase boundary</p>
              <div className="vx-scroll mt-4 max-h-64 space-y-2 overflow-y-auto pr-1">
                {(status.phaseLedger ?? []).map((row) => (
                  <div key={row.id} className={cn("border-l-2 py-0.5 pl-2 text-xs", row.status.includes("complete") ? "border-trust" : row.status.includes("in flight") ? "border-gold" : "border-edge")}>
                    <div className="flex items-center justify-between gap-2">
                      <span className="font-mono font-semibold text-body">Phase {row.phase}</span>
                      <span className={row.status.includes("complete") ? "text-trust" : row.status.includes("in flight") ? "text-warnx" : "text-mutedfg"}>
                        {row.status.replace("✅ ", "").replace("▶ ", "").replace("❌ ", "")}
                      </span>
                    </div>
                    <p className="line-clamp-2 text-mutedfg">{row.evidence}</p>
                  </div>
                ))}
                {(status.phaseLedger ?? []).length === 0 && <p className="text-xs text-mutedfg">ledger unavailable</p>}
              </div>
            </Panel>
          </div>
        </Section>
      ) : null}

      {status ? (
        <Section tight label="Outlook" title="Next work & technical risks">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
            <Panel className="p-6">
              <p className="flex items-center gap-2 text-sm font-semibold text-body">
                <ArrowRight className="h-4 w-4 text-gold" aria-hidden /> Recommended next work
              </p>
              <ol className="mt-3 list-inside list-decimal space-y-2 text-sm text-mutedfg">
                {status.nextWork.map((w, i) => (
                  <li key={i}>{w}</li>
                ))}
              </ol>
            </Panel>
            <Panel className="p-6">
              <p className="text-sm font-semibold text-body">Technical risks</p>
              <ul className="mt-3 list-inside list-disc space-y-2 text-sm text-mutedfg">
                {status.risks.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            </Panel>
          </div>
        </Section>
      ) : null}

      <Section tight label="Of record" title="Reports & documentation of record">
        <div className="flex items-start gap-3">
          <BookOpen className="mt-1 h-4 w-4 shrink-0 text-mutedfg" aria-hidden />
          <div className="flex flex-wrap gap-2">
            {["BUILD_REPORT.md", "VERIFICATION_REPORT.md", "ARCHITECTURE_REPORT.md", "ROADMAP_PROGRESS.md", "CHANGELOG.md", "SECURITY.md", "LEGAL.md", "docs/CLI.md", "docs/SDK.md", "docs/LIMITATIONS.md", "docs/RELEASE-NOTES-v0.1.14-rc1.md", "docs/ga/GO-NO-GO.md", "docs/ga/ASCENSION-XXVI-COMPLETION-REPORT.md", "docs/ga/REMAINING-REALITY-REPORT.md", "docs/founder/FOUNDER-PACKETS.md"].map((f) => (
              <Pill key={f}>{f}</Pill>
            ))}
          </div>
        </div>
        {status ? (
          <p className="mt-6 font-mono text-xs text-mutedfg">substrate · {status.substrate}</p>
        ) : null}
      </Section>
    </>
  );
}
